package {
    import flash.events.Event;
    import flash.display.Loader;
    import flash.text.TextField;
    import flash.display.Sprite;
    import mx.utils.Base64Decoder;
    public class FlashTest extends Sprite {
        public function FlashTest() {
            var d:Base64Decoder = new Base64Decoder;
            // http://www.google.co.jp/404
            d.decode(<><![CDATA[
                iVBORw0KGgoAAAANSUhEUgAAAKsA
                AADVCAMAAAAfHvCaAAAAGFBMVEVY
                n+H///+ex+3U5vd7s+fq8/s0itq7
                2PMLUPvtAAASvklEQVR4AbXBC0Jq
                CQxEwT5Jd7L/Hc8FdR4g+EGtEr8u
                /BHxu7otdzd/QPyqlmRp1Pw+8auk
                DfRa1fw28ZtWy4sa89vEb7LCi0zx
                28RvqgkvouW3id/U8pbtWmv5beJX
                RWNrRmp+nfhlHXZm+QPi95Vk/oD4
                fZbMHxC/ryTzB8Tva435A+L3rcb8
                AfH7VjJ/QPy+HYk/IH5facwfEL8i
                aZcrnKyn+APi57K2VL2WF1hJ/AHx
                Q2tJrg6HteXVjPkD4ge6V3J1+F97
                zhx+nXhWb8nacKXlnYPErxNPyfqw
                4ZYKVuUZdfhd4hmxunY73NICgfWM
                Ovwm8ZQ1pMvlDZdaCic98kjV4beI
                p8ScpLvsSvhflzqQmqVLB281v0E8
                pc2bdNne8EayNTPNSbt02PBj4int
                cKltb/NibY+Lf9aSO/yMeMo6XMva
                3g0vwrWsxvyMeEoc3knZ2g53ZaXa
                8DzxlHa4J23Jae5aycXTxFPa4WRd
                XAtdsivckZXG4TniKWtOSlre6y7L
                G651Wxq5OzxDPGUVIKNwX6ekCv+0
                ddglVPMM8ZQ10FJ4LGVvOEuXRl7O
                qnmGeEor4Ck+tnI1ZEvjDa/cPEM8
                ZQVY4RO9VqUlN/84PEM8JQ50cUgX
                H2mrKlyq5RniOQ4vVjPLHdu86OKG
                i2eIr+gNV6JwljmYO6zlbJsbWp4h
                PtVrjYpLLV7UHIp7rOVkixtaniE+
                U5I2Nc2FKJytZhTuiac5rLnh4hni
                EzUbDjXhn3g5W0nNA1aAKm7YPEN8
                bMecrZYLWl70hkcyBay5YfMM8aHI
                4aR7xAUVHyirOdhAmRsqniE+tOKs
                RjIXtDzmmRGHVmDFDRfPEB+JzMmO
                01xScdYnVRs6vPHMFG9W4ZrMM8RH
                ouWw43DNhlDWiSVZY3nDoWYc3qzD
                NZlniPe6w4uoOFjcKhPXuJNWyG6V
                qjSuhm7+iZorUfEM8U5J8nKyMw0t
                cZLwPxdRtTlUcUgVdGlml0uZ4pqK
                Z4hr5VUnpSXdUgVa4hA5vHERV1Tp
                9XhdJTWHksYd/tdarql4hrjQiaPi
                YLclNSeebVYz5o0W7Ghsa9blmlFt
                x01rxP8yy5XIPEP8L1W7bjWHlbzh
                RTwjzXrCK1f3qqSEyBysLVtayKp4
                0yqurcITxJtUgavVHNob/inZTWt5
                VVvWVKvJSttQCkRjb/A4vLK5thOe
                IN6sm9ai5cTFhYRDy/yTGpdU0hxk
                aZvWUrZluTmLims14QniVbywClqg
                eouT9IZXNWoupGzNqHa3y5LGVYBn
                ipbCSVxcq1meIN54oRXsbEk26S3N
                mBcZ807K3gon2ZLcxF5tPMVJprlW
                E54g3nihtbRHm7WjkbxTHSCWwj1r
                2U4HSMmdQEmWwonNtah4gnhjA9ZS
                aohmpnpDjWRptDwS25LcQGsc2Bla
                5sTFtZV4gnixpWmIVWpgRuVwsiV5
                q7kv0JJcNVIFapydUrHTQKa5IfME
                cRKrurSQ0qhsmVR4kea+7pIr9NqS
                rRltWlaxomUgVVyLxBPEYeUGygts
                zew2KfOBclVpVN2ctCXNidZaaKWm
                ONhc6rKaJwi6xuGkRmWpAkRa7out
                F9XN/7LlmbJmpiCyvBxk/tnSqHmG
                WGk5i2ZcaWBLau5KKHt3Ce/saLMz
                46VG4cTFm/aMOzxFUYWztjzhkNI4
                3JPyYvPAegPxzFRpOYmWF1WywrPU
                ag5xjRapqqxxubijvYFVaC/v7YSD
                pzxjzlbhpKXxhqcpWshqtECk0Yys
                6m5utZdD1LCuCifhfyVOapqsxhyi
                QMmSm58QNdZheZGV5FqwueXiZBUg
                a28DvRte1NQCpQVSUkFqPbIr/Ixg
                7arwJqqEg6e5Vuas1Zytyw1ka5uT
                9ajKI87WbksaLT8mbkXFyWqaa2rO
                VuFVStUNpGrDoSTPmDfWdlby8kPi
                HQtoa0vLpXU4WzX/S5W2gWxtOHQ2
                4U3CSUmu8BPinR2XVSFyuNAOZ9Fy
                ae1qDu2qcF8suRKeJt7pcW1zaE9x
                wcVZq7nWtpeTrQ0PrEeq8CTxnsWr
                lbThELra5ixqbsXWNoeq6nBft6Tl
                OeK9VnG2lfb4TKOOlpOouKPsWg4p
                b3Nf1uMGusP3iDtKDaTcgMuWvL1F
                mZOouCtlbwJs1Yb7SuN2Nd8k7mgv
                XV4OKWALiGkVJ14eyPqQQG9Vc0dW
                Gnn5LnFPTW1z1gW0OdSyag5aHsva
                roVs1YZL2dKMt1nzXeKulas52QLa
                nGy3xq4a87Eu2yHZ2uZNWzPjDbDm
                u8R9a8m7iQNscbKyy+WS+UzWtqp7
                qzpA1jPj8KKK7xIPZG2NVWTTSbpK
                bs5cfEF6y64qV6ctqcKbdvgm8VhS
                lnWwJbuaV3LzRb11onFt+KcVvkl8
                one7u3bD/zJuXnRt+FTXVHOWqubQ
                4rvEEyI1L1Z2h8+0eRHLKiBqvkk8
                IePmxZq1lk+0w0nJUHKIlm8ST8io
                eVEFtFwbPhA3h8gcdpZV803iCRkV
                L7Y42bK2w0NlDqXlpJRV803iGZYr
                nFRxlqwO3eEuN4dSOGlVme8Sz7C3
                7QZqeZPekl0b3nMBreKsp1bNN4ln
                WIEtF1Vc6i1bVZtwxQX0NC9UrfBN
                4hk7zaHLNrey1kgVLljATnO2rmj5
                JvEMqzlrF++FXitcsAArnFkdLd8k
                nrFqPmFzyQq0xUm0tJZvEs8oAR0e
                ix0u1ARSqg70NNHyTeIZUqgZ85gd
                LlgcMjOSRlBqvkk8wwOSp3moJlyo
                CYfeKkmBVvgm8YyaUJJ5zOJSTXMW
                Sgus+C7xjJpA+MiquVATXiUcSuGb
                xDNqmk+UxtW82WmurMI3iWd4wifa
                Ho1rNxx2miul8E3iGTXhc4nH0lQ1
                O80VK3yTeEYNX5SspbEnXFmFbxLP
                qGm+rsvWFFdK4ZvEM2rCt6RmzCWL
                7xLP2Anfs2M3Fyy+SzyjpvmqDoed
                5YrFd4ln7DRftHI19BRXSuGbxDN6
                wtdEqjF4lisS3yWeEYUvWlkDNeZK
                Tfgm8ZFu7mqFr/KMYae4lFH4JvGB
                VLgraghf09uQMZdabr5JfKC2q1zV
                3IgarOLLPMWllptvEo+1e7dkq5Zr
                Lkip+Kqa4lLk5ZvEY15INay9XIqX
                VGS+qsdcirzclYVa7hAPbQFVnJSa
                C9HCapavqjGXIjXvbNmSxi7eE4+s
                A21OumwuSQUJX1ZjLsVabqR6t7tU
                lrThhnjEC/Fy6AKbCy45zdftmEut
                Km5UcSgHspY7XBEPVAFVHLoCUXPF
                kr3hi2wutba44QDr5iyeqQ3/iAcc
                qOLQDhAV17pG0jZfUuZS5OJaGYiW
                F+2ypOV/4q5UQZtDu4G2xK10aeTl
                C1bhUslciQpYh7PSQtau8ErcVYZ4
                gXYDcUXLe1lrvBU+0VoutFRcWQWo
                4qwdTlYSr8Q9caDMwc3BDgl3xZpR
                b/ORnuVCJHNlla2oOYmLQ8q7Ll6I
                e6pgDaQKSCl8IF3WqAgPrbgU2Vxp
                V1kje2EdoOWGlsOJuKMd1g14OdjN
                p1YjNY+0m0s15kYgJVlaFxBVOETu
                AOK9eEELrDmUli/o8oy94S4Xl2Lz
                QGukEFU46RptQLy3BWWgHSBTvEp3
                2eGRtjTjSriQBKLlShUPrSRcnK2q
                tIB4Zw3tQNRAbF5FB0vhoS57JFXz
                ZmUtuLiy5gNlTTixlkgB8Y4byhAX
                0HJ4Y/cmWkjz0NrSaMNJ5EiNi3/S
                pPlIayqA3UBcIG5tQTuwBcQOJx3A
                srSzxHJ4bKs9U5xoqWnK4U17+UzP
                FLQ4iQ3iRtxQC3gBK5xZJjOutcaS
                peYjsUZqKFmGOLxIaflU1jI2ZzuL
                uLGuLe2yBlrLC1tdWg7ZmWal8KHe
                GtXG0gLLSdZyha+oKYdDl7WIGxpb
                I7lSicyLqFkH2rVZF+wUnymNXNu8
                WUkVLqSaB6IpIGWXF3Ft1UC6rRq3
                mhc7TRXgLS2lrKb5VEoz6nCSrtE2
                V6p4aMeQ8tJaxLU4nGU9o+XVTrMF
                +LBgjYqvSNkjL+Dxhmut5tDb3CF1
                uwJoEdday6vMTHjVs7GA3g3QU8tX
                xZJc6Q23yhxWckPCtZW1nLgQ12KF
                F5Ed3pQ0U7yKp/i6YM/I4dZOA3FR
                RdvhSmaWMxtxI3JzVlP8k9qsVFWd
                bVvTfENCjcytUoBW46XscE3DizLi
                1o6KQ4/DlZRsWSfBCt+SdHGrzGHF
                OtjFtUgNNJQR78Qjr+VwzV4I65Sa
                zPJzrQbKq6bl5kapU7bbRryXLo3c
                3LATYIfMEs3yc1bA44bScqumvJ21
                jLgrhHdSktNWkONR+LmULMnbpQm3
                pOWkZxHf0R7NKKykDr9iq3ptuexO
                uJQRZ5lCfE96K5Ct5iNpe118WQKx
                VeGCxnYDmUL8iUjb2+XmexIu9Di9
                XtgpxJ9wcehuOzwt1gJx4ynEM9K9
                tS5X7fLempP2dmnDczwjTlLYi/iC
                nHXSe9LWic9k3qvlRTltLU+p2lE1
                sKUG8bm2DiNpNBpJu5vwwuEdLa/W
                y6p4JL27Dg+0pUBsQHxu67C1Vb2d
                pLlU5h3bG87aS0vNXWtJtip0bbjD
                hqgB8TkvH1g115qttnfDoW0oNe+1
                Rs0hlqVRc8cSmYP4XBUfUXHNlQ5t
                qzkpNaXmHVV4lVpq1NxjhYP43JqP
                2FwracOh7OZQDuXmRmu5sjMO75SW
                E/E5F4/09s5wI5abQ0rFoVxZNTes
                7e7wvy053NpwJj7n4kVCDt29teWy
                pJHFOy0VJ6sN0CrK4dpakmv5pxQe
                EZ8rQ+9alnU2knyo2k64Ix4vh5I5
                sVNarqW3u8z/4mkeEZ8LrCxXtbfW
                u9t8qqQK0DKHVtEubrWm+Z9VPCS+
                JN1828oB4gqwalrFtUjNP3bzkPg7
                sdXAyhyssF4upWb5Z8c8Jv5QWmpg
                VRxUsGoulMw/PQqPiZ/p8JGVOLQW
                KAW6+CcyF2qGD4gfibe2ead5lXED
                pQAu0rv8r2WgtZxl1Twm/tls1HxH
                K7HDjZV51VIgWmBlSeMKr+xseZYX
                q+Ux8aY0MxrvVnUC4XNxgYtrJY15
                taMmNlAztd0lhxfW6MChC1rFY+LV
                jlwzKutVdfhE7xjKXEiX3CuHFzWG
                0lLycogUXnTtxuaws6DiMfFK09kZ
                Q9K1VSvJ3oRHslIFWuGftdzQUoWz
                lYONinBILRdaC8TTYPO/3nBFnKxL
                G2um+KfXOrg6vBdLrvJSCm9SJpy0
                RtucrMRq1Zy1woUy0B4HbN60ex0u
                iEN0KLk1xZXs2paKW9FIqrJrzP/s
                5k17tJz0GE/xohwulGElOUTmTRWl
                5oI4lKRRsTPhVpIdc6sl10IsFW9W
                XNpROPH0TkGAVnFpx5a63WSKN5HV
                XBKwc1btEffsNO8kvBObS5lZTnaU
                MXFYqbnUltwg75h/usMVATXleWW7
                qk1Xb8KLVfiKlsIlj9Sc1FhFtjIT
                boSTlSp8QMCO5JU11bb1ZlQdIHL4
                iprmktWROclqGlaWmvsSPiRAIy3l
                cAhk05vsWgfbU3xFVFyRWTUvSqqa
                2S7zHEFmRikt7yS18kxxFj6yY67U
                bNu86U6qIApPEUSasZb7Ek0DqXh5
                LHa4lDFWc6kd4uUpgsiaKR6pKQ61
                uHmsZrmyk1ZxpQ1oeYoAzaG4ry1z
                suXisVJxpeQdc60N2DxFgGckc1eP
                ixdpHkjVjrnS0kpc6u5SwMtTBKxk
                ybUJN3bUfCaulsMVTVvNP+myNQVe
                7tjlE+JFb1mSLVfV9jaHHS2fiao1
                5sqOd4pL29ArbxXvldV8TPwv6XVV
                6YXtGTefiiqaMRei2TFXKpzUONxK
                FWo+Jt5J0ltlzQxfsCqimSpv86Km
                rHApBbXA2s2NuKPwMfFQvOELWgvs
                nEjVQMYtc2UXqjm0xI0yq/Ax8T0J
                tyJz8DiekWpjxWoupRqqOamp5VJP
                sXJt9256wz3iW8oOt1xNaWah3NZJ
                ZK7UAg6HLo+5tFPgke2SreUe8R1r
                O9xayTpALFaa2Z3mUhyo4qQ6I67M
                bLlsyyfFPeI71m7ey0orw2pL256W
                uFILVHOI41mu1IyK3u0q28094nvC
                XQHLtqyF9Gq5tA7E4bAViRsrNW/C
                XeK3lDTVVoBI4ZIDVHFYpbTcyIbP
                iF/TSbPT3SUtl6qAuDl4W8UzxC/z
                6CRciALUcijT4inil/V2p4pLtUDc
                wCol8xTxF8KlKg5VQGtb4jniz7Ub
                WAcox+JJ4s+5OLiAVnuKJ4m/tuaw
                BURbszxL/LF4OXgh9s7yNPHHqjis
                gVLLPE/8rXYD7UCrVsXzxN+q4uAG
                rFj8gPhTXRzKwGprmh8Qf2rlot2A
                vSp+Qvyl1nikAlprh58Qf0lqolGB
                arX8iPhLZWBVqnVsfkb8pTaHcru6
                1PyM+EtrDq2UW8sPib/UChBvbIcf
                En/KxWGrpeWnxJ9qVYDyVPgp8bfa
                2qRmmh8Tf21lq5qfE38uveE3/Adr
                385/SVd/MAAAAABJRU5ErkJggg==
            ]]></>);
            var _onload:Function;
            var ldr:Loader = new Loader;
            ldr.loadBytes(d.toByteArray());
            ldr.contentLoaderInfo.addEventListener(Event.COMPLETE, _onload = function (e:Event):void {
                ldr.contentLoaderInfo.removeEventListener(Event.COMPLETE, _onload);
                
                ldr.x = (465 - ldr.width) >> 1;
                ldr.y = (465 - ldr.height) >> 1;
            });
            addChild(ldr);
        }
    }
}
